# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: Cypress tests

on:
  push:
    branches:
      - 'master'
      - 'dev'
      - '^(feature-.*|feature/.*)$'
      - '^(fix-.*|fix/.*)$'
      - '^(hotfix-.*|hotfix/.*)$'
      - '^(refactor-.*|refactor/.*)$'
      - '^(test-.*|test/.*)$'
    paths:
      - '.github/workflows/*'
      - 'packages/**'
      - 'scripts/**'
      - 'tests/**'
      - 'build/**'
      - 'cypress/**'
      - 'babel.config.json'
      - 'cypress.json'

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:latest
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
          node-version: '18'
    - name: Install dependencies
      run: yarn install
    - name: Build packages
      run: yarn build  
    - uses: cypress-io/github-action@v2
      with:
        browser: chrome
        start: yarn run example
        wait-on: 'http://localhost:8881/examples/default-mode.html'
