name: Cypress tests

on:
  push:
    branches:
      - 'master'
      - 'dev'
      - '^(dev-.*|dev/.*)$'
      - '^(feature-.*|feature/.*)$'
      - '^(fix-.*|fix/.*)$'
      - '^(hotfix-.*|hotfix/.*)$'
      - '^(refactor-.*|refactor/.*)$'
      - '^(test-.*|test/.*)$'
    paths:
      - '.github/workflows/*'
      - 'packages/**'
      - 'scripts/**'
      - 'tests/**'
      - 'build/**'
      - 'cypress/**'
      - 'babel.config.json'
      - 'cypress.json'
  pull_request:
    branches:
      - master

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v4

      # 设置 Node.js 版本
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 启用 Corepack
      - name: Enable Corepack
        run: corepack enable

      # 安装并激活 Yarn 4.x
      - name: Prepare Yarn
        run: corepack prepare yarn@4.4.1 --activate

      # 加载依赖缓存
      - name: Load cached dependencies
        uses: actions/cache@v4.1.1
        id: cache
        with:
          path: |
            **/node_modules
            **/.turbo
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}


      # 安装项目依赖
      - name: Install dependencies
        run: yarn install

      # 构建项目
      - name: Build packages
        run: yarn build

      # 运行 Cypress 测试
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: yarn run example
          wait-on: 'http://localhost:8881/examples/default-mode.html'
